name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        env:
          LOG_LEVEL: ${{secrets.LOG_LEVEL}}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.3000 }}
        run: yarn jest:test

      - name: Build project
        run: yarn build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > key.pem
          chmod 600 key.pem
          scp -i key.pem -o StrictHostKeyChecking=no -r ./dist user@server:/path/to/deploy
          ssh -i key.pem -o StrictHostKeyChecking=no user@server 'pm2 restart your-app'
